### ISSUE TITLE
Minimal Value can be Higher Than 255 Characters

### ISSUE THREAD

**Issue by LeoNerdoG** [lorthirk/kapua#8]
User can enter higher minimal password value than 255 (in this case 999999999). 
So it is no possible to enter password, becasue the limit is 255. 

**Testflow:**
1. Login as kapua-sys
2. Go to Accounts, create an account (e.g. acco0)
3. Select acc0, go to Account settings, change password.min.lenght to 999999999
4. Change infinite child users to True
5. Try to create a user - it is not possible, because min length pass is bigger than max length

**Expected behavior**
minimal password should be resticted to 254.

**Screenshots**
![Screenshot 2020-10-28 at 08 24 42](https://user-images.githubusercontent.com/15121999/97412776-4b5dce80-1902-11eb-961b-a778af3414b4.png)

**Version of Kapua**
 https://github.com/lorthirk/kapua/tree/feature-configurablePasswordLength

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API -> did not try rest api!!! -> please check!
[ ] Message Broker
[ ] - Others

**Comment by lorthirk** [comment]
Uhm... Why minimum should be 243?

**Comment by LeoNerdoG** [comment]
Well...the system defauly is 12, right? so if user is able to set min password to e.g. 250, that is 5 characters long passwrod, which is not compliant with the system setting? also password with only e.g. 5 characters is weak in its nature. What do you think?

**Comment by lorthirk** [comment]
Uhm... if min password is 250, it means that the password can be anything between 250 and 255 long. I honestly still can't get your point 😄

**Comment by LeoNerdoG** [comment]
shit crap, sorry, I am stupid. 
Yeah, youa re right. Brain freeze. Updated issue 😄

**Comment by lorthirk** [comment]
I decided to allow up to 255, just in case someone wants exactly 255. I know the message would sound silly, but I really don't think anyone would set 255 anyway.

**Comment by LeoNerdoG** [comment]
I have verified that this issue has been fixed.
